server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

file:
  dir: /Users/yeong-geun/desktop/spring/jwt/src/main/resources/images/

cloud:
  aws:
    s3:
      bucket: antiimages
    stack:
      auto: false
    credentials:
      access-key: AKIAWMX3F6GELISNKVM2
      secret-key: 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
    region:
      static: ap-northeast-2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cos
    password: jsjs9797
  h2:
    console:
      enabled: true


  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
